/**
 * Getting the invoice out: as a PDF, and as its own source.
 *
 * ----- the PDF -----
 *
 * There is no PDF library in here, and that is the design rather than a corner
 * cut. Every option was worse:
 *
 *   A PDF writer (pdf-lib, jsPDF) means laying the page out a second time, in a
 *   second coordinate system, with its own font metrics. Two layout engines for
 *   one document is how the export comes to disagree with the preview, and the
 *   disagreement always shows up on somebody else's invoice.
 *
 *   A rasteriser (html2canvas and friends) produces a picture of a page. The
 *   text stops being text: it cannot be searched, copied, or read aloud, it
 *   prints soft, and the file is twenty times the size.
 *
 *   The browser already has a typesetter with a PDF backend, and it is the same
 *   one that drew the preview. Handing it the very component that is on
 *   screen, drawn with editing off, means the output is the preview by
 *   construction, with live text, vector rules and a real page size.
 *
 * The cost is that the user meets the system print dialog and has to choose
 * "Save as PDF" there. That is a genuine cost and it is the right trade: it is
 * one familiar dialog, and in exchange the file is correct.
 *
 * ----- the JSON -----
 *
 * The document is offered as a file because an invoice is a record, and a
 * record you cannot get out of the tool that made it is hostage. It is the
 * whole document, pretty-printed, with no app state in it, which means it can
 * be committed, diffed, templated, generated by a script, and hand-edited. The
 * importer expects exactly that and repairs what it finds, so a file somebody
 * has been at with a text editor still opens.
 */

import { createElement } from 'react'
import { flushSync } from 'react-dom'
import { createRoot } from 'react-dom/client'
import { ui } from '../lib/ui'
import { track } from '../lib/analytics'
import { InvoicePaper, PAPER_ID } from './InvoicePaper'
import { useInvoice } from './store'
import { migrateDoc, PAGE_SIZE, type InvoiceDoc } from './types'

/** A filename that sorts and reads well: `INV-0007-northwind.invoice.json`. */
export function fileStem(doc: InvoiceDoc): string {
  const slug = (s: string) =>
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40)
  return [slug(doc.number), slug(doc.to.name)].filter(Boolean).join('-') || 'invoice'
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  // a frame is enough for the click to be handled; revoking synchronously
  // cancels the download in Safari
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

/** The document as it is written to a file: pretty, stable, app state free. */
export function docJSON(doc: InvoiceDoc): string {
  return JSON.stringify(doc, null, 2)
}

export function downloadJSON(doc: InvoiceDoc) {
  downloadBlob(
    new Blob([docJSON(doc)], { type: 'application/json' }),
    `${fileStem(doc)}.invoice.json`,
  )
  track('export_completed', { editor: 'invoice', format: 'json' })
}

export async function copyJSON(doc: InvoiceDoc) {
  await navigator.clipboard.writeText(docJSON(doc))
  ui.toast('Invoice JSON copied')
}

/**
 * Read a `.invoice.json` back.
 *
 * Every failure here is a file the user chose on purpose, so each one gets a
 * specific message rather than a generic refusal: they can act on "that file is
 * not an invoice" and they can do nothing at all with "import failed".
 */
export async function readInvoiceFile(file: Blob): Promise<InvoiceDoc | null> {
  let parsed: unknown
  try {
    parsed = JSON.parse(await file.text())
  } catch {
    ui.error('That file is not valid JSON')
    return null
  }
  const doc = migrateDoc(parsed)
  if (!doc) {
    ui.error('That JSON is not an invoice this version can open')
    return null
  }
  return doc
}

/** Offer a file picker, and hand back what it opened. */
export function pickInvoiceFile(onDoc: (doc: InvoiceDoc) => void) {
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = 'application/json,.json'
  input.onchange = () => {
    const f = input.files?.[0]
    if (!f) return
    void readInvoiceFile(f).then((doc) => {
      if (doc) {
        onDoc(doc)
        ui.toast(`Opened ${doc.number}`)
      }
    })
  }
  input.click()
}

/**
 * Every stylesheet in the document, as text.
 *
 * The print frame is a separate document and inherits nothing, so the app's CSS
 * has to travel with the node. Tailwind ships as one injected `<style>` in dev
 * and one linked file in the build, and both come back through
 * `document.styleSheets`; a sheet from another origin throws on `cssRules` and
 * is skipped, which is correct, since nothing cross-origin styles this page.
 */
function collectCSS(): string {
  const out: string[] = []
  for (const sheet of Array.from(document.styleSheets)) {
    try {
      for (const rule of Array.from(sheet.cssRules)) out.push(rule.cssText)
    } catch {
      /* cross-origin: not ours, and not styling the paper */
    }
  }
  return out.join('\n')
}

/**
 * Print the page that is on screen.
 *
 * Drawn again rather than cloned. The page on screen is full of inputs, hover
 * tools and "+ Add" chips, and a clone would carry every one of them into the
 * PDF, along with textareas whose typed text lives in a property the clone
 * does not copy. Rendering the same component into the frame with editing off
 * gives the page exactly as it prints, from the same code that drew it.
 *
 * The frame is a real same-origin document rather than an `srcdoc` one, for a
 * specific reason: the logo is shown through a blob URL, and a blob URL only
 * resolves in a document that shares the origin that created it. `srcdoc`
 * frames are treated as opaque by some engines and the mark silently vanishes
 * from the PDF, which is the single worst place for it to vanish from.
 */
export async function printInvoice(doc: InvoiceDoc) {
  const page = PAGE_SIZE[doc.look.page]

  const frame = document.createElement('iframe')
  frame.setAttribute('aria-hidden', 'true')
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:1px;height:1px;opacity:0;border:0'
  document.body.appendChild(frame)

  const win = frame.contentWindow
  const fdoc = frame.contentDocument
  if (!win || !fdoc) {
    frame.remove()
    ui.error('This browser would not open a print view')
    return
  }

  fdoc.open()
  fdoc.write('<!doctype html><html><head><meta charset="utf-8"></head><body></body></html>')
  fdoc.close()

  const style = fdoc.createElement('style')
  style.textContent = `
    ${collectCSS()}
    /* the sheet is the whole document here: no margins, no chrome, no scroll */
    @page { size: ${page.css}; margin: 0; }
    html, body {
      margin: 0; padding: 0; background: #fff; height: auto; overflow: visible;
    }
    /*
     * Backgrounds and colours are the invoice, not ink the browser may drop to
     * save toner: the accent rule and the stamp are meaning, so both vendor
     * spellings are set and both are needed in the field.
     */
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
    #${PAPER_ID} {
      width: ${page.w}px !important;
      height: ${page.h}px !important;
      transform: none !important;
      box-shadow: none !important;
      border-radius: 0 !important;
      break-inside: avoid;
    }
  `
  fdoc.head.appendChild(style)

  // `flat` lands the stamp settled: a print fired while the live one is still
  // animating must not capture the mark mid-flight
  const host = fdoc.createElement('div')
  fdoc.body.appendChild(host)
  const root = createRoot(host)
  flushSync(() =>
    root.render(createElement(InvoicePaper, { doc, logoUrl: useInvoice.getState().logoUrl, flat: true })),
  )

  /*
   * Print only once everything it draws has arrived. An unloaded logo prints as
   * a blank box, and a font that resolves a frame late re-flows the table after
   * the snapshot was taken. Both are silent, and both are only visible in the
   * file the client receives.
   */
  try {
    await Promise.all([
      ...Array.from(fdoc.images).map((img) =>
        img.complete
          ? Promise.resolve()
          : new Promise<void>((res) => {
              img.onload = () => res()
              img.onerror = () => res()
            }),
      ),
      fdoc.fonts?.ready ?? Promise.resolve(),
    ])
  } catch {
    /* a font or image that never settles is not a reason to refuse to print */
  }

  track('export_started', { editor: 'invoice', format: 'pdf' })
  win.focus()
  win.print()
  track('export_completed', { editor: 'invoice', format: 'pdf' })

  /*
   * The frame outlives the print call, because `print()` returns as soon as the
   * dialog is up in some browsers and the document has to still exist while the
   * user is choosing a destination. `afterprint` is the signal where it fires;
   * the timeout is the backstop where it does not, and it is long enough to
   * cover somebody reading their own print dialog.
   */
  const done = () => {
    clearTimeout(timer)
    root.unmount()
    frame.remove()
  }
  const timer = window.setTimeout(done, 60_000)
  win.addEventListener('afterprint', done, { once: true })
}
