/**
 * The style registry.
 *
 * A style is not a mode with its own code path, it is a painter (or a
 * whole-frame process) plus a short list of facts about what it needs. The
 * panel reads those facts to decide which controls to show, the renderer reads
 * them to decide how to cut the grid, and the exporter reads `glyph` to decide
 * whether text output is even meaningful. Everything asking one table means a
 * new style is a row here and a function in `painters.ts` or `process.ts`, and
 * nothing else in the app has to learn about it.
 *
 * `group` is behaviour (how the renderer treats it) and `family` is where it
 * sits in the picker. They are kept apart on purpose: Low poly behaves like a
 * tile and reads as geometry, Thermal is a process and reads as light.
 */

import {
  Aperture,
  AudioWaveform,
  Binary,
  Blocks,
  Box,
  BrickWall,
  Brush,
  Building2,
  ChartColumn,
  Circle,
  CircleDot,
  CloudRain,
  Contrast,
  Diamond,
  Droplets,
  Flame,
  Gem,
  Glasses,
  Grip,
  GripVertical,
  Hash,
  Heart,
  Hexagon,
  LayoutGrid,
  Lightbulb,
  Map as MapIcon,
  Menu,
  Mountain,
  Newspaper,
  Paintbrush,
  Palette,
  PenTool,
  Pencil,
  Plus,
  Printer,
  Ruler,
  ScanLine,
  Shapes,
  Shirt,
  Slash,
  Snowflake,
  Sparkles,
  Spline,
  SprayCan,
  Squircle,
  Stamp,
  Star,
  Sun,
  Table,
  TextQuote,
  Thermometer,
  Triangle,
  Type,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { GRADIENTS } from './gradients'
import { amount, choice, color, range, toggle, type ParamSpec } from './params'
import type { AsciiStyleId } from './types'

export type StyleGroup = 'glyph' | 'shape' | 'raster' | 'process'

/** Where a style sits in the picker. */
export type StyleFamily = 'type' | 'marks' | 'tiles' | 'print' | 'paint' | 'light'

export interface StyleSpec {
  id: AsciiStyleId
  label: string
  group: StyleGroup
  family: StyleFamily
  /**
   * The glyph on the style's button, where a button is drawn rather than a
   * thumbnail. Chosen to depict what the painter actually draws rather than to
   * label the category.
   */
  icon: LucideIcon
  /** draws characters from a ramp, so .txt, ANSI, HTML and SVG all work */
  glyph: boolean
  /** forces square cells: a LEGO brick with a 1.8 aspect is not a LEGO brick */
  square: boolean
  /** honours the grout slider */
  gap: boolean
  /** reads the character ramp, so the character set picker applies */
  ramp?: boolean
  /** one line, shown under the pointer and in the section's info dot */
  hint: string
  /** settings beyond the shared grid and tone */
  params?: ParamSpec[]
  /** a starting cell size, for styles that are unreadable at the text default */
  cell?: number
}

const paper = (def = '#f3efe6') => color('paper', 'Paper', def)
const ink = (def = '#16140f') => color('ink', 'Ink', def)
const gradientChoice = (key: string, label: string, def: string) =>
  choice(key, label, GRADIENTS.map((g) => ({ id: g.id, label: g.label })), def)

export const STYLES: StyleSpec[] = [
  // ----- type -----
  {
    id: 'characters',
    label: 'Characters',
    icon: Type,
    group: 'glyph',
    family: 'type',
    glyph: true,
    ramp: true,
    square: false,
    gap: false,
    hint: 'Text from a character set, darkest character for the darkest cell.',
  },
  {
    id: 'blocks',
    label: 'Blocks',
    icon: Squircle,
    group: 'glyph',
    family: 'type',
    glyph: true,
    square: false,
    gap: false,
    hint: 'Shade blocks instead of letters. Solid, and it tiles without seams.',
  },
  {
    id: 'braille',
    label: 'Braille',
    icon: GripVertical,
    group: 'glyph',
    family: 'type',
    glyph: true,
    square: false,
    gap: false,
    hint: 'Eight dots per cell, so it resolves four times the vertical detail.',
  },
  {
    id: 'contour',
    label: 'Contour type',
    icon: Slash,
    group: 'glyph',
    family: 'type',
    glyph: true,
    ramp: true,
    square: false,
    gap: false,
    hint: 'Slashes and bars laid along the edges, like a line drawing typed out.',
    params: [
      range('threshold', 'Edge', 0.02, 0.8, 0.16, { fmt: 'pct', hint: 'How strong an edge must be to get a stroke' }),
      toggle('fill', 'Fill shapes', true),
    ],
  },
  {
    id: 'rain',
    label: 'Code rain',
    icon: CloudRain,
    group: 'glyph',
    family: 'type',
    glyph: true,
    ramp: true,
    square: false,
    gap: false,
    hint: 'Falling columns of glyphs, each with a bright head.',
    params: [range('trail', 'Trail', 4, 60, 16, { fmt: 'int' })],
  },
  {
    id: 'typeset',
    label: 'Word fill',
    icon: TextQuote,
    group: 'glyph',
    family: 'type',
    glyph: true,
    square: false,
    gap: false,
    hint: 'Your own words repeated through the picture, inked by the tone.',
    params: [{ kind: 'text', key: 'text', label: 'Words', def: 'RIBBIT ' }],
  },

  // ----- marks -----
  {
    id: 'dots',
    label: 'Dots',
    icon: Grip,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'A disc per cell, sized by how dark the cell is. Halftone by hand.',
  },
  {
    id: 'rings',
    label: 'Rings',
    icon: CircleDot,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'Hollow circles, growing into the shadows.',
    params: [range('weight', 'Weight', 0.04, 0.5, 0.14, { fmt: 'pct' })],
  },
  {
    id: 'lines',
    label: 'Lines',
    icon: Menu,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: false,
    gap: true,
    hint: 'A horizontal rule per cell, thickening into the shadows.',
  },
  {
    id: 'waves',
    label: 'Waves',
    icon: AudioWaveform,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: false,
    gap: false,
    hint: 'One continuous wave per row, swelling where the picture is dark.',
    params: [range('height', 'Height', 0.1, 1.6, 0.9, { fmt: 'x' }), range('period', 'Wavelength', 0.5, 12, 3, { fmt: 'x' })],
  },
  {
    id: 'diagonals',
    label: 'Diagonals',
    icon: Slash,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'Forty-five degree hatching, the way an engraving shades.',
  },
  {
    id: 'hatch',
    label: 'Crosshatch',
    icon: Hash,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Layer on layer of hatching, a new direction for every step of shadow.',
    params: [range('weight', 'Weight', 0.03, 0.4, 0.12, { fmt: 'pct' })],
  },
  {
    id: 'strokes',
    label: 'Flow',
    icon: Wind,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Brush strokes that follow the picture’s own contours.',
    params: [range('length', 'Length', 0, 3, 1.1, { fmt: 'x' }), amount(0.25, 'Wander', 'wander')],
  },
  {
    id: 'stipple',
    label: 'Stipple',
    icon: Sparkles,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Tone from how many dots, not how big. Pen and ink.',
    params: [range('dots', 'Dots per cell', 1, 16, 6, { fmt: 'int' }), range('size', 'Dot size', 0.03, 0.3, 0.09, { fmt: 'pct' })],
    cell: 12,
  },
  {
    id: 'cross',
    label: 'Cross',
    icon: Plus,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'A plus per cell. Reads as a technical grid.',
  },
  {
    id: 'diamond',
    label: 'Diamond',
    icon: Diamond,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'A rotated square per cell, which packs tighter than a disc.',
  },
  {
    id: 'hexes',
    label: 'Hex',
    icon: Hexagon,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'A hexagon per cell, sized by the shadow.',
  },
  {
    id: 'triangles',
    label: 'Triangles',
    icon: Triangle,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'Alternating up and down, so the marks nest into each other.',
  },
  {
    id: 'weave',
    label: 'Truchet',
    icon: Spline,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Quarter arcs that join across cells into one long winding path.',
    params: [range('weight', 'Weight', 0.05, 0.9, 0.4, { fmt: 'pct' })],
    cell: 14,
  },
  {
    id: 'stars',
    label: 'Stars',
    icon: Star,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'A five-point star per cell.',
    params: [range('pinch', 'Point', 0.2, 0.9, 0.45, { fmt: 'pct' })],
  },
  {
    id: 'hearts',
    label: 'Hearts',
    icon: Heart,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'A heart per cell. For when it is that kind of picture.',
  },
  {
    id: 'bars',
    label: 'Meter',
    icon: ChartColumn,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: false,
    gap: true,
    hint: 'A level meter per cell, standing on its floor.',
    params: [range('width', 'Bar width', 0.2, 1, 0.7, { fmt: 'pct' })],
  },
  {
    id: 'mixed',
    label: 'Mixed',
    icon: Shapes,
    group: 'shape',
    family: 'marks',
    glyph: false,
    square: true,
    gap: true,
    hint: 'A different mark in every cell, chosen by position rather than at random.',
  },

  // ----- tiles -----
  {
    id: 'pixel',
    label: 'Pixel art',
    icon: LayoutGrid,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Solid tiles in the source colours. The grid, with nothing drawn on it.',
  },
  {
    id: 'mosaic',
    label: 'Mosaic',
    icon: Table,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: true,
    hint: 'Tiles with grout between them, each one lit slightly differently.',
  },
  {
    id: 'honeycomb',
    label: 'Honeycomb',
    icon: Hexagon,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: true,
    hint: 'Hexagonal tiles on offset rows, no gaps between them.',
  },
  {
    id: 'leadlight',
    label: 'Stained glass',
    icon: Gem,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: true,
    hint: 'Saturated panes held in dark lead.',
    params: [range('glow', 'Colour', 1, 3, 1.6, { fmt: 'x' }), color('lead', 'Lead', '#141414')],
  },
  {
    id: 'lego',
    label: 'Bricks',
    icon: Blocks,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'A studded toy brick per cell, lit from above.',
  },
  {
    id: 'beads',
    label: 'Fuse beads',
    icon: Circle,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Plastic beads on a pegboard, the hole in each one showing.',
    params: [color('board', 'Board', '#e9e6df')],
  },
  {
    id: 'knit',
    label: 'Knit',
    icon: Shirt,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'A V of yarn per cell. Your picture as a jumper.',
  },
  {
    id: 'led',
    label: 'LED wall',
    icon: Lightbulb,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Round LEDs on a dark board, brighter where the picture is.',
    params: [color('board', 'Board', '#0b0c0d')],
  },
  {
    id: 'neon',
    label: 'Neon grid',
    icon: Zap,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: true,
    hint: 'Glowing outlines, a tube per cell.',
  },
  {
    id: 'facets',
    label: 'Low poly',
    icon: Triangle,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Each cell folded into two facets along the picture’s own grain.',
  },
  {
    id: 'voxel',
    label: 'Voxel',
    icon: Box,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Isometric cubes, standing taller the denser the cell. Invert to flip it.',
  },
  {
    id: 'terrace',
    label: 'Skyline',
    icon: Building2,
    group: 'raster',
    family: 'tiles',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Slabs raised by the shadow, like a city or a contour model.',
    params: [range('height', 'Height', 0.2, 3, 1.4, { fmt: 'x' })],
  },

  // ----- print -----
  {
    id: 'dither',
    label: 'Dither',
    icon: Binary,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Error diffusion or an ordered mask, quantised to a retro palette.',
  },
  {
    id: 'halftone',
    label: 'Press',
    icon: Printer,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Four rotated dot screens, cyan, magenta, yellow and black, the way magazines print.',
    params: [
      range('cell', 'Dot pitch', 3, 40, 9, { fmt: 'px' }),
      choice('mode', 'Screens', [
        { id: 'cmyk', label: 'CMYK' },
        { id: 'mono', label: 'One ink' },
      ]),
      ink('#16140f'),
      paper('#f7f4ec'),
    ],
  },
  {
    id: 'riso',
    label: 'Riso',
    icon: Stamp,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Two fluorescent drum inks, grainy and slightly out of register.',
    params: [
      color('inkA', 'Ink one', '#ff48b0'),
      color('inkB', 'Ink two', '#0078bf'),
      paper('#f4efe6'),
      range('grain', 'Grain', 1, 8, 3, { fmt: 'px' }),
      range('shift', 'Misregister', 0, 20, 4, { fmt: 'px' }),
    ],
  },
  {
    id: 'mezzotint',
    label: 'Mezzotint',
    icon: SprayCan,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Tone from a random screen, velvety in the blacks.',
    params: [
      range('grain', 'Grain', 1, 8, 1, { fmt: 'px' }),
      choice('screen', 'Screen', [
        { id: 'dots', label: 'Grain' },
        { id: 'worms', label: 'Worms' },
      ]),
      ink(),
      paper(),
    ],
  },
  {
    id: 'engrave',
    label: 'Engraving',
    icon: PenTool,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Parallel lines swelling into the shadows and bending over the form, like a banknote.',
    params: [
      range('spacing', 'Spacing', 2, 20, 5, { fmt: 'px' }),
      range('angle', 'Angle', 0, 180, 30, { fmt: 'deg' }),
      amount(0.5, 'Bend', 'bend'),
      ink('#1b1f2a'),
      paper('#f1ede2'),
    ],
  },
  {
    id: 'woodcut',
    label: 'Woodcut',
    icon: Mountain,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Bold black shapes with gouge marks cut through the light.',
    params: [range('threshold', 'Black at', 0.1, 0.8, 0.38, { fmt: 'pct' }), range('cuts', 'Cut spacing', 2, 16, 5, { fmt: 'px' }), ink('#141210'), paper('#efe6d2')],
  },
  {
    id: 'comic',
    label: 'Comic',
    icon: Newspaper,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Flat colour, a heavy ink line, and dots in the shadows.',
    params: [range('levels', 'Colours', 2, 8, 4, { fmt: 'int' }), amount(0.6, 'Line', 'line'), range('dots', 'Dot pitch', 3, 20, 6, { fmt: 'px' })],
  },
  {
    id: 'poster',
    label: 'Screenprint',
    icon: Palette,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Brightness pulled into a few flat bands of ink.',
    params: [range('levels', 'Bands', 2, 10, 4, { fmt: 'int' }), gradientChoice('gradient', 'Inks', 'sunset')],
  },
  {
    id: 'popart',
    label: 'Pop art',
    icon: LayoutGrid,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Repeated in a grid, every copy in its own three inks.',
    params: [
      choice('grid', 'Grid', [
        { id: '2', label: '2 × 2' },
        { id: '3', label: '3 × 3' },
      ]),
      range('levels', 'Cut', 0.2, 0.9, 0.55, { fmt: 'pct' }),
      range('shift', 'Inks', 0, 8, 0, { fmt: 'int' }),
    ],
  },
  {
    id: 'cyanotype',
    label: 'Cyanotype',
    icon: Sun,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'A Prussian blue sun print, brushed on by hand.',
    params: [amount(0.5, 'Exposure', 'exposure'), amount(0.5, 'Brushed edge', 'brush')],
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    icon: Ruler,
    group: 'process',
    family: 'print',
    glyph: false,
    square: true,
    gap: false,
    hint: 'White linework on drafting blue, over a grid.',
    params: [range('grid', 'Grid', 4, 60, 16, { fmt: 'px' }), amount(0.5, 'Lines', 'lines'), color('paper', 'Blue', '#123a7a')],
  },

  // ----- paint -----
  {
    id: 'sketch',
    label: 'Pencil',
    icon: Pencil,
    group: 'process',
    family: 'paint',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Graphite outlines, with light hatching in the shadows.',
    params: [amount(0.6, 'Lines', 'lines'), amount(0.5, 'Shading', 'shade'), ink('#2a2a2e'), paper('#f6f4ef')],
  },
  {
    id: 'oil',
    label: 'Oil paint',
    icon: Paintbrush,
    group: 'process',
    family: 'paint',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Flat, confident strokes that keep the edges. Kuwahara, for the curious.',
    params: [range('brush', 'Brush', 1, 16, 5, { fmt: 'px' }), amount(0.5, 'Canvas', 'canvas')],
  },
  {
    id: 'watercolor',
    label: 'Watercolour',
    icon: Droplets,
    group: 'process',
    family: 'paint',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Soft washes with pigment pooling at their edges, on textured paper.',
    params: [range('wash', 'Wash', 1, 14, 4, { fmt: 'px' }), amount(0.6, 'Edges', 'edges'), amount(0.6, 'Paper', 'paper')],
  },
  {
    id: 'pointil',
    label: 'Pointillism',
    icon: Brush,
    group: 'process',
    family: 'paint',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Dabs of pure colour, the eye doing the mixing.',
    params: [range('size', 'Dab', 2, 30, 7, { fmt: 'px' }), amount(0.4, 'Vivid', 'vivid'), paper('#f2ede1')],
  },
  {
    id: 'crystal',
    label: 'Crystallize',
    icon: Snowflake,
    group: 'process',
    family: 'paint',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Broken into irregular cells, each one flat colour.',
    params: [range('size', 'Cell', 4, 80, 18, { fmt: 'px' }), amount(0, 'Borders', 'edges')],
  },
  {
    id: 'topo',
    label: 'Topography',
    icon: MapIcon,
    group: 'process',
    family: 'paint',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Contour lines of equal brightness, like an elevation map.',
    params: [
      range('levels', 'Contours', 3, 40, 14, { fmt: 'int' }),
      range('weight', 'Weight', 0.3, 4, 1, { fmt: 'px' }),
      toggle('fill', 'Elevation colour', true),
      gradientChoice('gradient', 'Colours', 'forest'),
      ink('#2b2418'),
      paper('#f1ecdf'),
    ],
  },

  // ----- light -----
  {
    id: 'thermal',
    label: 'Thermal',
    icon: Thermometer,
    group: 'process',
    family: 'light',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Brightness read as heat, through a thermal camera’s palette.',
    params: [
      choice(
        'palette',
        'Palette',
        [
          { id: 'thermal', label: 'Iron' },
          { id: 'flir', label: 'Infrared' },
          { id: 'lava', label: 'Lava' },
          { id: 'arctic', label: 'Arctic' },
          { id: 'nightvision', label: 'Night vision' },
        ],
        'thermal',
      ),
      range('soften', 'Soften', 0, 12, 3, { fmt: 'px' }),
      amount(0.2, 'Sensor noise', 'noise'),
    ],
  },
  {
    id: 'glowedge',
    label: 'Edge glow',
    icon: Flame,
    group: 'process',
    family: 'light',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Only the outlines, glowing in their own colour on black.',
    params: [amount(0.5, 'Gain', 'gain'), amount(0.6, 'Glow', 'glow')],
  },
  {
    id: 'relief',
    label: 'Relief',
    icon: Contrast,
    group: 'process',
    family: 'light',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Pressed into metal, lit from one side.',
    params: [range('light', 'Light from', 0, 360, 225, { fmt: 'deg' }), amount(0.5, 'Depth', 'depth'), toggle('color', 'Keep colour')],
  },
  {
    id: 'anaglyph',
    label: 'Anaglyph',
    icon: Glasses,
    group: 'process',
    family: 'light',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Red and cyan offsets, for the cardboard glasses.',
    params: [amount(0.4, 'Depth', 'depth'), toggle('pop', 'Bright things float', true)],
  },
  {
    id: 'pixelsort',
    label: 'Pixel sort',
    icon: ScanLine,
    group: 'process',
    family: 'light',
    glyph: false,
    square: true,
    gap: false,
    hint: 'Runs of pixels sorted by brightness, so the picture melts in streaks.',
    params: [
      range('low', 'From', 0, 1, 0.25, { fmt: 'pct' }),
      range('high', 'To', 0, 1, 0.8, { fmt: 'pct' }),
      choice('direction', 'Direction', [
        { id: 'across', label: 'Across' },
        { id: 'down', label: 'Down' },
      ]),
      toggle('reverse', 'Reverse'),
    ],
  },
]

const BY_ID = new Map(STYLES.map((s) => [s.id, s]))

export function getStyle(id: AsciiStyleId): StyleSpec {
  return BY_ID.get(id) ?? STYLES[0]
}

/** True for the styles drawn as one whole frame rather than cell by cell. */
export function isProcess(id: AsciiStyleId): boolean {
  return getStyle(id).group === 'process'
}

export const STYLE_FAMILIES: { id: StyleFamily; label: string; icon: LucideIcon }[] = [
  { id: 'type', label: 'Type', icon: Type },
  { id: 'marks', label: 'Marks', icon: Shapes },
  { id: 'tiles', label: 'Tiles', icon: BrickWall },
  { id: 'print', label: 'Print', icon: Printer },
  { id: 'paint', label: 'Paint', icon: Paintbrush },
  { id: 'light', label: 'Light', icon: Aperture },
]

/** kept for callers that grouped by behaviour */
export const STYLE_GROUPS: { id: StyleGroup; label: string }[] = [
  { id: 'glyph', label: 'Text' },
  { id: 'shape', label: 'Marks' },
  { id: 'raster', label: 'Tiles' },
  { id: 'process', label: 'Process' },
]
